# Generated by Django 5.0.5 on 2024-05-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
